- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: check-xml
    - id: check-symlinks
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-case-conflict
    - id: check-byte-order-marker
    - id: check-added-large-files
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: no-go-testing
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
